import { useState, useEffect } from "react";
import { Terminal, Cpu, Play, CheckCircle2, ChevronRight, HelpCircle, Loader2, Sparkles, FileText } from "lucide-react";
import { GoogleGenAI } from "@google/genai";

export default function ComputerPanel() {
  const [taskInput, setTaskInput] = useState("");
  const [status, setStatus] = useState<"idle" | "planning" | "executing" | "writing" | "done">("idle");
  const [logs, setLogs] = useState<string[]>([]);
  const [resultCode, setResultCode] = useState("");
  const [activeTaskTitle, setActiveTaskTitle] = useState("");

  const handleRunTask = () => {
    if (!taskInput.trim()) return;

    setActiveTaskTitle(taskInput.trim());
    setStatus("planning");
    setLogs(["[system] Received new task delegation...", "[agent] Analyzing task parameters & designing workflow maps"]);
    setResultCode("");

    // Step-by-step simulation to make it feel extremely alive
    setTimeout(() => {
      setStatus("executing");
      setLogs((prev) => [
        ...prev,
        "[agent] Workflow compiled. Bootstrapping isolated node runtime container...",
        "[system] Port 3000 mapped successfully. Initializing node core packages...",
        "[command] npm install express @google/genai dotenv tsx",
        "[system] Installed 14 dependencies in 840ms",
        "[agent] Beginning command-line script extraction and target directory scan..."
      ]);
    }, 1500);

    setTimeout(() => {
      setLogs((prev) => [
        ...prev,
        "[agent] Setting up server entrypoint point at root: /server.ts",
        "[command] tsx check-health.ts --env=production",
        "[system] Production health checks validated. Resolving modules...",
        "[agent] Engineering main automation routines inside sandboxed memory..."
      ]);
    }, 3200);

    setTimeout(() => {
      setStatus("writing");
      setLogs((prev) => [
        ...prev,
        "[agent] Automation logic finalized. Formulating verified deliverables...",
        "[system] Output files matching directory schemas compiled into `/dist/*` successfully."
      ]);
      setResultCode(
        `/**
 * @license Apache-2.0
 * Verified automation output generated by PointAI Computer Agent.
 */
import express from 'express';
import { GoogleGenAI } from '@google/genai';

const app = express();
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// Automated target keyword extraction routine
app.post('/api/automation/extract', async (req, res) => {
  const { datasetText } = req.body;
  
  const response = await ai.models.generateContent({
    model: 'gemini-3.5-flash',
    contents: \`Extract key frequency keyword maps from this corpus: \${datasetText}\`,
  });

  res.json({
    status: 'success',
    vocabularyMaps: response.text,
    generatedAt: new Date().toISOString()
  });
});

app.listen(3000, () => {
  console.log('Automated sandbox server online.');
});`
      );
    }, 5500);

    setTimeout(() => {
      setStatus("done");
      setLogs((prev) => [
        ...prev,
        "[system] Core automation pipelines closed successfully.",
        "[agent] Task completely solved. Deliverables deployed and finalized! 🚀"
      ]);
    }, 7000);
  };

  return (
    <div className="max-w-[800px] mx-auto px-4 pt-12 pb-16 text-left animate-fade-in">
      <div className="border-b border-slate-100 pb-5 mb-8">
        <div className="flex items-center gap-2">
          <h1 className="text-3xl font-sans font-light text-primary tracking-tight">Computer Agent</h1>
          <span className="bg-emerald-100 text-emerald-800 text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider">New Beta</span>
        </div>
        <p className="text-on-surface-variant text-sm mt-1">
          Delegate complex coding, compiling, scraping, or math automation tasks directly to a sandboxed terminal model.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Input & Controllers */}
        <div className="flex flex-col gap-4 lg:col-span-1">
          <div className="bg-white border border-outline-variant rounded-2xl p-5 flex flex-col gap-4 shadow-xs">
            <h3 className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1.5">
              <Cpu className="w-4 h-4 text-slate-800" /> Delegate New Project
            </h3>
            
            <textarea
              value={taskInput}
              onChange={(e) => setTaskInput(e.target.value)}
              disabled={status !== "idle" && status !== "done"}
              placeholder="e.g. Write a production-ready Express server that implements real-time text frequency counts and has test cases."
              rows={4}
              className="bg-slate-50 border border-slate-205 rounded-xl p-3 text-xs focus:ring-1 focus:ring-slate-300 outline-none resize-none font-sans"
            />

            <button
              onClick={handleRunTask}
              disabled={(status !== "idle" && status !== "done") || !taskInput.trim()}
              className={`w-full rounded-lg py-3 text-xs font-semibold flex items-center justify-center gap-2 cursor-pointer transition-all ${
                (status !== "idle" && status !== "done") || !taskInput.trim()
                  ? "bg-slate-100 text-slate-300 cursor-not-allowed"
                  : "bg-black hover:bg-slate-800 text-white shadow-xs active:scale-95"
              }`}
            >
              {status !== "idle" && status !== "done" ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin text-slate-400" />
                  <span>Agent Working...</span>
                </>
              ) : (
                <>
                  <Play className="w-4 h-4" />
                  <span>Execute Automation</span>
                </>
              )}
            </button>
          </div>

          <div className="bg-slate-50 border border-slate-150 rounded-xl p-4 flex flex-col gap-2.5">
            <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-1">
              <HelpCircle className="w-3.5 h-3.5" /> sandbox parameters
            </h4>
            <div className="flex items-center justify-between text-xs text-slate-600">
              <span>Environment:</span>
              <span className="font-semibold text-slate-800 font-mono">Node.js Ubuntu</span>
            </div>
            <div className="flex items-center justify-between text-xs text-slate-600">
              <span>Active Ports:</span>
              <span className="font-semibold text-slate-800 font-mono">3000 (Proxy mapped)</span>
            </div>
            <div className="flex items-center justify-between text-xs text-slate-600">
              <span>Memory Limit:</span>
              <span className="font-semibold text-slate-800 font-mono">512MB Core VM</span>
            </div>
          </div>
        </div>

        {/* Live Execution Screen */}
        <div className="lg:col-span-2 flex flex-col gap-4">
          {/* Terminal stream console */}
          <div className="bg-[#1c1b1b] rounded-2xl p-5 text-white font-mono text-[11px] h-72 flex flex-col justify-between shadow-md">
            <div className="flex items-center justify-between border-b border-slate-850 pb-2 mb-2 text-slate-400">
              <span className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                <Terminal className="w-3.5 h-3.5" /> Live Agent Operations Console
              </span>
              <div className="flex items-center gap-1">
                <span className="w-2 h-2 rounded-full bg-red-500"></span>
                <span className="w-2 h-2 rounded-full bg-amber-500"></span>
                <span className="w-2 h-2 rounded-full bg-green-500"></span>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto custom-scrollbar flex flex-col gap-1 pr-1 pb-4">
              {logs.length === 0 ? (
                <span className="text-slate-500 italic">Terminal sitting idle. Enter a task instruction on the left and select 'Execute' to begin...</span>
              ) : (
                logs.map((log, idx) => {
                  let color = "text-slate-100";
                  if (log.startsWith("[system]")) color = "text-yellow-400";
                  if (log.startsWith("[command]")) color = "text-cyan-400";
                  if (log.startsWith("[agent]")) color = "text-emerald-400";
                  
                  return (
                    <div key={idx} className={`leading-relaxed text-left border-l-2 pl-2 ${
                      log.startsWith("[agent]") 
                        ? "border-emerald-500/50" 
                        : log.startsWith("[system]") 
                        ? "border-yellow-500/50" 
                        : "border-transparent"
                    } ${color}`}>
                      {log}
                    </div>
                  );
                })
              )}
            </div>
          </div>

          {/* Compiled sandbox outputs */}
          {resultCode && (
            <div className="bg-white border border-outline-variant rounded-2xl p-5 shadow-xs animate-fade-in text-left">
              <h4 className="text-xs font-bold text-slate-800 uppercase mb-3 flex items-center gap-1.5 border-b border-slate-50 pb-2">
                <FileText className="w-4 h-4 text-slate-800" /> Compiled Output File: <span className="font-mono text-black">/server.ts</span>
              </h4>
              <div className="bg-slate-50 hover:bg-slate-50/50 border border-slate-150 p-4 rounded-xl max-h-56 overflow-y-auto custom-scrollbar">
                <pre className="text-[11px] text-slate-700 font-mono select-all text-left">
                  {resultCode}
                </pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
